spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/springTest
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api

