spring:
  datasource:
    url: jdbc:h2:mem:mProducts
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  servlet:
    context-path: /api